apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: react-counter-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /react-counter
      - /react-counter/ # Добавили вариант со слэшем для надежности
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-counter
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # Важен порядок! Сначала HTTPS, потом StripPrefix
    traefik.ingress.kubernetes.io/router.middlewares: |
      default-force-https@kubernetescrd,
      default-react-counter-stripprefix@kubernetescrd
spec:
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /react-counter
            pathType: Prefix # Позволяет ловить и /react-counter, и /react-counter/assets/...
            backend:
              service:
                name: react-counter
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
