apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: react-counter-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /react-counter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-counter
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # 1. Сначала заставляем перейти на HTTPS
    # 2. Затем отрезаем префикс /react-counter, чтобы Nginx внутри пода его не видел
    traefik.ingress.kubernetes.io/router.middlewares: |
      default-force-https@kubernetescrd,
      default-react-counter-stripprefix@kubernetescrd
spec:
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /react-counter
            pathType: Prefix
            backend:
              service:
                name: react-counter
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
