apiVersion: v1
kind: Service
metadata:
  name: react-counter # Это имя должен использовать Ingress
  namespace: default
spec:
  selector:
    app: react-counter-app # Это должно совпадать с labels в Deployment
  ports:
    - port: 80
      targetPort: 80 # Порт внутри контейнера (Nginx)
  type: ClusterIP
